<?php

declare(strict_types=1);

namespace Vanssa\SyliusSliderPlugin\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    /**
     * @psalm-suppress UnusedVariable
     */
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('vanssa_sylius_slider');
        $rootNode = $treeBuilder->getRootNode();
        /** @var ArrayNodeDefinition $rootNode */

        $rootNode
            ->children()
                ->arrayNode('presets')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('slider')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('container_width')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['content', 'full'])->end()
                                        ->scalarNode('default')->defaultValue('full')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('spacing')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['0', '0.5rem', '1rem', '1.5rem', '2rem', '4rem'])->end()
                                        ->scalarNode('default')->defaultValue('0')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('slide_effect')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['slide', 'fade', 'zoom', 'lift', 'flip'])->end()
                                        ->scalarNode('default')->defaultValue('slide')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('navigation_icon')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['chevron', 'angle', 'square'])->end()
                                        ->scalarNode('default')->defaultValue('chevron')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('navigation_size')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['1.5rem', '3rem', '4rem', '6rem'])->end()
                                        ->scalarNode('default')->defaultValue('3rem')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('navigation_shadow')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['none', 'soft', 'medium', 'strong', 'glow'])->end()
                                        ->scalarNode('default')->defaultValue('none')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('pagination_shape')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['circle', 'square'])->end()
                                        ->scalarNode('default')->defaultValue('circle')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('pagination_size')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['0.5rem', '0.625rem', '0.8rem', '1rem'])->end()
                                        ->scalarNode('default')->defaultValue('0.625rem')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('pagination_shadow')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['none', 'soft', 'medium', 'strong', 'glow'])->end()
                                        ->scalarNode('default')->defaultValue('none')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('autoplay_interval')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->integerPrototype()->end()->defaultValue([2000, 3000, 5000, 8000, 10000])->end()
                                        ->integerNode('default')->defaultValue(5000)->end()
                                    ->end()
                                ->end()
                                ->arrayNode('parallax_strength')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['0.5rem', '1rem', '2rem', '3rem', '4rem'])->end()
                                        ->scalarNode('default')->defaultNull()->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('slide')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('headline_element')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['div', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'])->end()
                                        ->scalarNode('default')->defaultValue('div')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('content_horizontal_position')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['start', 'left_2_12', 'left_3_12', 'left_4_12', 'center', 'right_2_12', 'right_3_12', 'right_4_12', 'end'])->end()
                                        ->scalarNode('default')->defaultValue('start')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('content_vertical_position')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['top', 'top_1_5', 'top_2_5', 'top_3_5', 'top_4_5', 'center', 'bottom'])->end()
                                        ->scalarNode('default')->defaultValue('bottom')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('content_text_align')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['left', 'center', 'right'])->end()
                                        ->scalarNode('default')->defaultValue('left')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('content_animation')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['fade-up', 'fade-right', 'zoom-in', 'none'])->end()
                                        ->scalarNode('default')->defaultValue('fade-up')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('animation_duration')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->integerPrototype()->end()->defaultValue([250, 400, 500, 700, 1000])->end()
                                        ->integerNode('default')->defaultValue(500)->end()
                                    ->end()
                                ->end()
                                ->arrayNode('animation_delay')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->integerPrototype()->end()->defaultValue([0, 100, 200, 350, 500])->end()
                                        ->integerNode('default')->defaultValue(0)->end()
                                    ->end()
                                ->end()
                                ->arrayNode('background_blur_preset')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['none', 'soft', 'medium', 'strong'])->end()
                                        ->scalarNode('default')->defaultValue('none')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('content_blur_strength')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->integerPrototype()->end()->defaultValue([4, 8, 12, 16, 24])->end()
                                        ->integerNode('default')->defaultValue(12)->end()
                                    ->end()
                                ->end()
                                ->arrayNode('content_padding')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['0', '0.75rem', '1rem', '1.5rem', '2rem'])->end()
                                        ->scalarNode('default')->defaultValue('1rem')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('content_margin')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['0', '0.5rem', '1rem', '1.5rem', '2rem'])->end()
                                        ->scalarNode('default')->defaultValue('0')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('border_radius')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->integerPrototype()->end()->defaultValue([0, 6, 10, 16, 24])->end()
                                        ->integerNode('default')->defaultValue(0)->end()
                                    ->end()
                                ->end()
                                ->arrayNode('headline_font_size')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['0.8rem', '1rem', '1.2rem', '1.5rem', '2rem', '2.5rem', '3rem'])->end()
                                        ->scalarNode('default')->defaultValue('1.5rem')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('description_font_size')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['0.8rem', '1rem', '1.2rem', '1.5rem', '2rem', '2.5rem', '3rem'])->end()
                                        ->scalarNode('default')->defaultValue('1rem')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('button_font_size')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['0.8rem', '1rem', '1.2rem', '1.5rem', '2rem', '2.5rem', '3rem'])->end()
                                        ->scalarNode('default')->defaultValue('1.2rem')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('linking_type')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['custom', 'product', 'category'])->end()
                                        ->scalarNode('default')->defaultValue('custom')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('button_appearance')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['primary', 'secondary', 'success', 'danger'])->end()
                                        ->scalarNode('default')->defaultValue('primary')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('button_size')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['sm', 'md', 'lg'])->end()
                                        ->scalarNode('default')->defaultValue('md')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('button_position')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['content_left', 'content_center', 'content_right', 'slider_bottom_left', 'slider_bottom_left_2_12', 'slider_bottom_left_3_12', 'slider_bottom_left_4_12', 'slider_bottom_center', 'slider_bottom_right', 'slider_bottom_right_2_12', 'slider_bottom_right_3_12', 'slider_bottom_right_4_12'])->end()
                                        ->scalarNode('default')->defaultValue('content_left')->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('color_switcher')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('theme')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['classic', 'monolith', 'nano'])->end()
                                        ->scalarNode('default')->defaultValue('classic')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('default_representation')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('values')->scalarPrototype()->end()->defaultValue(['HEX', 'RGBA', 'HSLA', 'HSVA', 'CMYK'])->end()
                                        ->scalarNode('default')->defaultValue('RGBA')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('swatches')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('text')->scalarPrototype()->end()->defaultValue([
                                            'rgba(255, 255, 255, 1)',
                                            'rgba(255, 255, 255, 0.92)',
                                            'rgba(245, 245, 245, 1)',
                                            'rgba(230, 230, 230, 1)',
                                            'rgba(0, 0, 0, 1)',
                                        ])->end()
                                        ->arrayNode('neutral')->scalarPrototype()->end()->defaultValue([
                                            'rgba(0, 0, 0, 0)',
                                            'rgba(15, 23, 42, 0.75)',
                                            'rgba(17, 24, 39, 0.9)',
                                            'rgba(31, 41, 55, 0.85)',
                                            'rgba(255, 255, 255, 1)',
                                        ])->end()
                                        ->arrayNode('accent')->scalarPrototype()->end()->defaultValue([
                                            'rgba(250, 204, 21, 1)',
                                            'rgba(250, 204, 21, 0.75)',
                                            'rgba(250, 204, 21, 0.45)',
                                            'rgba(59, 130, 246, 0.85)',
                                            'rgba(244, 114, 182, 0.85)',
                                            'rgba(16, 185, 129, 0.85)',
                                            'rgba(245, 158, 11, 0.85)',
                                        ])->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
